### ISSUE TITLE
Fedora 36 Image

### ISSUE THREAD

**Issue by offa** [jhnc-oss/yocto-image#40]
Add a Fedora 36 image. 

_ETA: 10.05.2022_

https://fedorapeople.org/groups/schedule/f-36/f-36-key-tasks.html

**Comment by h5b** [comment]
:+1:

**Comment by offa** [comment]
Fedora 36 is in beta at the moment, final (end user) release date is _26.04.2022_.

**Comment by offa** [comment]
I'll keep this open until final release arrives.

**Comment by offa** [comment]
Once more delayed, new target date is 10.5.2022.

**Comment by offa** [comment]
Fedora 36 is available finally :tada:

**Comment by offa** [comment]
PR merged, image is available in the registry :+1:.
