### ISSUE TITLE
Drop 'latest' tag?

### ISSUE THREAD

**Issue by offa** [jhnc-oss/yocto-image#48]
Shall we drop the `latest` tag? In my opinion it doesn't make much sense to use in the Yocto scenario.

**Comment by h5b** [comment]
:+1:

**Comment by offa** [comment]
- [ ] EOL (Readme)
- [ ] Remove build
- [ ] Drop tag from registry (after some grace period)

**Comment by offa** [comment]
`latest` deleted from registry.
